### ISSUE TITLE
accessing creative apiary gui crashes client 

### ISSUE THREAD

**Issue by darkcamo12** [starforcraft/Creative-Apiary#1]
running All The Mods 6 version 1.5.10b 

placed the apiary and tried to open the gui only to be crashed out

crash log: https://pastebin.com/N8hsh210

**Comment by starforcraft** [comment]
Which Version of Resourceful Bees do you have in your client?

**Comment by starforcraft** [comment]
Hmm weird seems like Resourceful Bees changed something I will push a Update later :)
