### ISSUE TITLE
Crash when bees enter in the creative apiary

### ISSUE THREAD

**Issue by Inverseder** [starforcraft/Creative-Apiary#3]
Hello,
I have a problem with your mod when a bee enter in the creative apiary my game crash. I use the creative storage with creative apiary. I give you my crash report to fix the problem if it's possible. I try with the tier 4 apiary and I don't crash.

[crash-2021-08-14_19.09.05-server.txt](https://github.com/starforcraft/Creative-Apiary/files/6987576/crash-2021-08-14_19.09.05-server.txt)

**Comment by starforcraft** [comment]
Will be fixed in next Version :)

**Comment by starforcraft** [comment]
https://github.com/starforcraft/Creative-Apiary/commit/36596de7d6b7f193fc9acf8211b8b43b720fe758
