### ISSUE TITLE
[creativeapiary-1.16.5-1.72.jar] - Creative breeder not breeding 

### ISSUE THREAD

**Issue by joeltine** [starforcraft/Creative-Apiary#6]
I have a creative breeder installed in a tier 1 apiary and it's not successfully breeding bees. I'm running All the Mods 6 w/ creative apiary v. creativeapiary-1.16.5-1.72.jar. 

Currently, I'm just trying two dirty bees, dirt, and an empty bee jar (see attached screenshto). It's been running for a long time now and no successful breeding has happened yet. 

![2021-11-27_15 49 10](https://user-images.githubusercontent.com/13138272/143722525-a4d31eb7-f032-4225-b490-f8f6c2b85a25.png)

**Comment by starforcraft** [comment]
Reading Tooltip is always helpful :)

**Comment by joeltine** [comment]
OK, can you please be explicit? Does it need to be in the creative apiary for it to work?

**Comment by starforcraft** [comment]
![grafik](https://user-images.githubusercontent.com/60074805/143765225-c448c537-d920-4e82-bd6c-511803b4b9d4.png)
